export const TOPICS = [
    { name: 'Anime', emoji: '🍥' },
    { name: 'Furries', emoji: '🐾' },
    { name: 'Art', emoji: '🎨' },
    { name: 'Music', emoji: '🎵' },
    { name: 'Dance', emoji: '💃' },
    { name: 'Movies', emoji: '🎬' },
    { name: 'Games', emoji: '🎮' },
    { name: 'Photography', emoji: '📷' },
    { name: 'Travel', emoji: '✈️' },
    { name: 'Food', emoji: '🍽️' },
    { name: 'Fitness', emoji: '💪' },
    { name: 'Technology', emoji: '💻' },
    { name: 'Fashion', emoji: '👗' },
    { name: 'Books', emoji: '📚' },
    { name: 'Cooking', emoji: '👨‍🍳' },
    { name: 'Sports', emoji: '⚽' },
    { name: 'Cars', emoji: '🚗' },
    { name: 'Nature', emoji: '🌿' },
    { name: 'Space', emoji: '🚀' },
    { name: 'Science', emoji: '🔬' },
    { name: 'Comics', emoji: '💥' },
    { name: 'Cosplay', emoji: '🦸' },
    { name: 'Writing', emoji: '✍️' },
    { name: 'Crafts', emoji: '🧶' },
    { name: 'Philosophy', emoji: '🤔' },
    { name: 'History', emoji: '🏛️' },
    { name: 'Psychology', emoji: '🧠' },
    { name: 'Astronomy', emoji: '🌟' },
    { name: 'Programming', emoji: '👨‍💻' },
    { name: 'Pets', emoji: '🐶' }
];